config/routes.rb
Rails.application.routes.draw do
  resources Phrasing.route,
            as: :phrasing_phrases,
            controller: :phrasing_phrases,
            only: [:index, :edit, :update, :destroy] do
    collection do
      get  :help
      get  :import_export
      get  :download
      post :upload
    end
  end

  resources :phrasing_phrase_versions, only: :destroy
end

app/controllers/phrasing_phrases_controller.rb
require 'phrasing/string'

class PhrasingPhrasesController < Phrasing.parent_controller.constantize

  layout 'phrasing'

  protect_from_forgery

  include PhrasingHelper

  before_action :authorize_editor

  def import_export
  end

  def help
  end

  def index
    params[:locale] ||= I18n.default_locale
    @phrasing_phrases = phrasing_phrases
    @locale_names = PhrasingPhrase.distinct.pluck(:locale)
  end

  def edit
    @phrasing_phrase = PhrasingPhrase.find(params[:id])
  end

  def update
    request.xhr? ? xhr_phrase_update : phrase_update
  end

  def download
    app_name = Rails.application.class.to_s.split("::").first
    app_env = Rails.env
    time = Time.now.strftime('%Y_%m_%d_%H_%M_%S')
    filename = "phrasing_phrases_#{app_name}_#{app_env}_#{time}.yml"
    send_data Phrasing::Serializer.export_yaml(phrasing_phrases), filename: filename
  end

  def upload
    number_of_changes = Phrasing::Serializer.import_yaml(params["file"].tempfile)
    redirect_to phrasing_phrases_path, notice: "YAML file uploaded successfully! Number of phrases changed: #{number_of_changes}."
  rescue => e
    message = if params[:file].nil?
                'Please choose a file.'
              else
                'Please upload a valid YAML file.'
              end

    flash[:alert] = "There was an error processing your upload! #{message}"
    render action: 'import_export', status: 400
  end

  def destroy
    phrasing_phrase = PhrasingPhrase.find(params[:id])
    phrasing_phrase.destroy
    redirect_to phrasing_phrases_path, notice: "#{phrasing_phrase.key} deleted!"
  end

  private

  def authorize_editor
    redirect_to root_path unless can_edit_phrases?
  end

  def xhr_phrase_update
    klass, attribute = params[:klass], params[:attribute]

    return render status: 403, text: 'Phrase not whitelisted' unless Phrasing.whitelisted?(klass, attribute)
    return render status: 403, text: 'Edit mode is disabled' unless edit_mode?

    record = klass.classify.constantize.find(params[:id])

    if record.update(attribute => params[:new_value])
      render json: record
    else
      render status: 403, json: record.error.full_messages
    end
  end

  def phrase_update
    phrase = PhrasingPhrase.find(params[:id])
    phrase.value = params[:phrasing_phrase][:value]
    phrase.save!

    redirect_to phrasing_phrases_path, notice: "#{phrase.key} updated!"
  end

  def phrasing_phrases
    PhrasingPhrase.fuzzy_search(params[:search], params[:locale])
  end

  def edit_mode?
    Phrasing::String.new(params[:edit_mode_enabled]).to_bool
  end
end

app/views/phrasing_phrases/edit.html.haml
.edit
  %h2= @phrasing_phrase.key
  = link_to "Delete Phrase", phrasing_phrase_path(@phrasing_phrase), class: "btn btn-danger delete-phrase", method: :delete, data: { confirm: 'Are you sure?' }
  = form_for @phrasing_phrase, url: { action: "update" } do |f|
    = f.text_area :value, rows: 12
    = f.submit "Update", class: "btn btn-success submit-edit-phrase"
  %br
  - unless @phrasing_phrase.versions.empty?
    %br
    %h2 Previous Versions
    %br
    %table.phrase-versions
      %tr
        %th Value
        %th Created_at
        %th
        %th
      - @phrasing_phrase.versions.reverse.each do |version|
        %tr
          %td.phrasing-version-value= version.value.html_safe
          %td.phrasing-version-created_at= version.created_at.strftime("%d-%m-%Y %H:%M:%S")
          %td= link_to "Revert", phrasing_phrase_path(@phrasing_phrase.id, phrasing_phrase: {value: version.value}), class: "btn btn-success", method: :put
          %td= link_to "Delete", phrasing_phrase_version_path(version.id), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }

app/views/phrasing_phrases/help.html.haml
%div
  %div
    %p Phrasing is a Ruby on Rails engine that allows you to edit live website copy.
  %div
    %h2 How to use
    %p Search for the copy text you want to edit. If Phrasing is currently controlling that content, it will appear when you search. If not, ask a developer to add it to Phrasing. You can filter by locale to control what copy is displayed in different languages.
    %p Once copy appears, click the left hand side links to edit. Values with keys ending in "_html" will be parsed as literal html, so you can insert tags. All other values are parsed as plain text.
  %div
    %h2 Exporting and Importing
    %p Phrasing text is data--not code. By default, it is stored in your server's database, and not the codebase that powers your website. Therefore, you may have to download/upload Phrasing data to transfer your copy edits between servers, or to safeguard them between database wipes. Phrasing exports (and is able to re-import) all of its data in a plaintext format called "YAML."
    %h4 Exporting
    %p You can get a YAML file of all your copy by clicking "Download" on the Import/Export page.
    %h4 Importing
    %p You can upload copy to Phrasing by uploading a properly formatted YAML file on the Import/Export page. Uploading copy won't delete any entries from Phrasing, but it may update them or create new ones. Use this feature to mass-update your copy from between servers -- e.g., make changes to copy on a test server, and then when you're satisfied, download the YAML file and upload it to your production site. Downloading your copy as YAML and then immediately re-uploading it will leave your copy unchanged.
    %h4 Commiting copy to code
    %p
      If your copy has reached a stable state and you don't need to update it live anymore, you can download your copy as YAML and include it as part of the Ruby on Rails application underneath your main website. You can then remove Phrasing from the application entirely, and the website will still run exactly as before--it interfaces with Ruby on Rails's built-in translation mechanisms in a very unobtrusive way.

app/views/phrasing_phrases/import_export.html.haml
%h2 Import
%div
  %p
    Upload a YAML (.yml) file following
    = succeed "." do
      %a{href: "http://guides.rubyonrails.org/i18n.html"} I18n conventions
  = form_tag 'upload', multipart: true, :'accept-charset' => 'UTF-8' do
    = file_field_tag "file"
    = submit_tag "Upload"

%h2 Export
%div
  = link_to "Download as YAML", download_phrasing_phrases_path

app/views/phrasing_phrases/index.html.haml
#search
  = form_tag phrasing_phrases_path, method: :get do
    - locale_options = options_for_select([nil] + @locale_names.map{|l| [l,l]}, params[:locale])
    = select_tag 'locale', locale_options
    = text_field_tag :search, params[:search], placeholder: 'Search for keys or values', size: 40
    = submit_tag 'Search', class: "btn btn-success"
    = link_to 'Download', download_phrasing_phrases_path(search: params[:search], locale: params[:locale]), class: 'btn btn-success'

- if @phrasing_phrases.any?
  %table.all-phrases
    %thead
      %tr
        %th Key
        %th Value
    %tbody
      - @phrasing_phrases.each do |t|
        %tr{onclick: "document.location = '/#{Phrasing.route}/#{t.id}/edit'"}
          %td.key
            = link_to edit_phrasing_phrase_path(t) do
              = t.key
          %td.value
            = t.value.try(:html_safe)